"""Gaussian splat shot render + minimal SHARP pipeline (single custom node pack)."""

from __future__ import annotations

from .gaussian_shot_node import NODE_CLASS_MAPPINGS as _GAUSSIAN_NODE_CLASS_MAPPINGS
from .gaussian_shot_node import NODE_DISPLAY_NAME_MAPPINGS as _GAUSSIAN_NODE_DISPLAY_NAME_MAPPINGS
from .sharp_nodes.load_model import NODE_CLASS_MAPPINGS as _SHARP_LOAD_NODE_CLASS_MAPPINGS
from .sharp_nodes.load_model import NODE_DISPLAY_NAME_MAPPINGS as _SHARP_LOAD_NODE_DISPLAY_NAME_MAPPINGS
from .sharp_nodes.predict import NODE_CLASS_MAPPINGS as _SHARP_PREDICT_NODE_CLASS_MAPPINGS
from .sharp_nodes.predict import NODE_DISPLAY_NAME_MAPPINGS as _SHARP_PREDICT_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS: dict = {}
NODE_CLASS_MAPPINGS.update(_GAUSSIAN_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_SHARP_LOAD_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_SHARP_PREDICT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS: dict = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_GAUSSIAN_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_SHARP_LOAD_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_SHARP_PREDICT_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
